import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode = "windowed"
opacity = 0.8

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 14

[cursor]
style = "Beam"
[colors.cursor]
text = "#ffffff"
cursor = "#ffffff"


