require("vim._core.ui2").enable({})

require("options")
require("keymaps")
require("commands")
require("plugins.plugins")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.colorscheme")
require("plugins.git-stuff")
require("plugins.linting")
require("plugins.lsp")
require("plugins.ui")
vim.cmd.colorscheme("catppuccin-mocha")
